### ISSUE TITLE
Cannot uncheck some checkboxes in /me

### ISSUE THREAD

**Issue by daumann** [JedWatson/sydjs-site#122]
To reproduce, go to http://www.sydjs.com/me and try unchecking **When there is a new meetup** or **When there is a new post**

It won't apply the changes.

**Comment by daumann** [comment]
...which is quite critical because it basically makes it impossible to unset notifications (emails).

**Comment by rleddy** [comment]
I just ran into this and have a code change for routes/view/me.js
Basically, if the field is not checked on the form, then it is not included in the body object.

`	view.on('post', { action: 'profile.details' }, function(next) {

        if ( !('mentoring.available' in req.body) ) req.body['mentoring.available'] = false;
        if ( !('mentoring.paid' in req.body) ) req.body['mentoring.paid'] = false;
        if ( !('mentoring.swap' in req.body) ) req.body['mentoring.swap'] = false;
        if ( !('mentoring.free' in req.body) ) req.body['mentoring.free'] = false;

        req.body['mentoring.paid'] = req.body['mentoring.paid'] && req.body['mentoring.available'];
        req.body['mentoring.swap'] = req.body['mentoring.swap'] && req.body['mentoring.available'];
        req.body['mentoring.free'] = req.body['mentoring.free'] && req.body['mentoring.available'];

		req.user.getUpdateHandler(req).process(req.body, {
			fields: 'name, email, notifications.meetups, notifications.posts,' + 
			'website, isPublic, bio, photo,' + 
			'mentoring.available, mentoring.free, mentoring.paid, mentoring.swap, mentoring.have, mentoring.want',
			flashErrors: true
		}, function(err) {
		
			if (err) {
				return next();
			}
			
			req.flash('success', 'Your changes have been saved.');
			return next();
		
		});
	
	});
`

**Comment by daumann** [comment]
@rleddy to be complete:

```
        if ( !('mentoring.available' in req.body) ) req.body['mentoring.available'] = false;
        if ( !('mentoring.paid' in req.body) ) req.body['mentoring.paid'] = false;
        if ( !('mentoring.swap' in req.body) ) req.body['mentoring.swap'] = false;
        if ( !('mentoring.free' in req.body) ) req.body['mentoring.free'] = false;
        if ( !('isPublic' in req.body) ) req.body['isPublic'] = false;
        if ( !('notifications.meetups' in req.body) ) req.body['notifications.meetups'] = false;
        if ( !('notifications.posts' in req.body) ) req.body['notifications.posts'] = false;

        req.body['mentoring.paid'] = req.body['mentoring.paid'] && req.body['mentoring.available'];
        req.body['mentoring.swap'] = req.body['mentoring.swap'] && req.body['mentoring.available'];
        req.body['mentoring.free'] = req.body['mentoring.free'] && req.body['mentoring.available'];

```
This cries for re-factorization, but this works for now.
