### ISSUE TITLE
Thanks SydJS, forked in the wrong way and site is online!

### ISSUE THREAD

**Issue by cylim** [JedWatson/sydjs-site#134]
Hey guys,

I tried to fork the [sydjs-site](https://github.com/JedWatson/sydjs-site) and upgrade the keystone to version 4 in order to use Mailgun for mailing.

Unfortunately, I can't get it working, so that I start a new keystone project and copy everything from this repo. Due to inappropriate planning, I didn't solve issues one by one, which makes it harder to contribute back to this project.

Our site: [PenangJS](https://javascript.my)
Our forked: [Site](https://github.com/JSMY/site)

Not sure why the snowbag link isn't working in my version, I keep the Sydjs footer, users can refer back to this project if they wanted to. :)

**Comment by gautamsi** [comment]
snowbag doesnt work unless you create an organization named [`thinkmill`](https://github.com/JedWatson/sydjs-site/blob/4b77000909ea560cefbb18c0dfa78840834db87e/routes/views/showbag.js#L16).
