### ISSUE TITLE
Exit with code 243

### ISSUE THREAD

**Issue by mokuzuu** [JedWatson/sydjs-site#143]
Hello.

I tried to use concurrently for node & react project, however, it does not work with code 243.
```
user@user:~/Personal_Project/mern_practice$ npm start
test_1@1.0.0 start /home/user/Personal_Project/mern_practice
 concurrently "cd backend && node server.js" "cd client && npm start"
[1] cd client && npm start exited with code 243
```

In root directory, there are two sub directories, which are client (React) and server (node.js).
I made sure that each of sub directory runs fine respectively, but it does not work if I tried to run at same time with concurrently.

**Comment by msimpsondev** [comment]
okay, so what was the issue?

**Comment by msimpsondev** [comment]
I'm having the same problem and it's driving me up a fucking wall
