### ISSUE TITLE
Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by macbroadcast** [JedWatson/sydjs-site#36]
hello everybody , i believe i did everything right and followed your instruction and after i run, 
`node keystone` , i´ve got the following errors:

```
/development/sysjs-site/sydjs-site$ node keystone

module.js:340
    throw err;
          ^
Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/macbroadcast/development/sysjs-site/sydjs-site/keystone.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
/development/sysjs-site/sydjs-site$ 
```

**Comment by iksnae** [comment]
i've encounter this same issue when attempting to deploy to openshift

**Comment by akashchitlangia** [comment]
Please run this command to resolve this error. 

![image](https://user-images.githubusercontent.com/4955355/37655255-c3d57318-2c6a-11e8-9729-02d73315df4e.png)

**Comment by ShibinCo** [comment]
Issue Fixed. Thanks :)

**Comment by vipulhadiya** [comment]
I have the same issue even I have installed the module.

**Comment by rizerzero** [comment]
same here, I have this issue in a container (Gitlab CI).

**Comment by dhowe** [comment]
same here

**Comment by josephmtinangi** [comment]
> Please run this command to resolve this error.
> 
> ![image](https://user-images.githubusercontent.com/4955355/37655255-c3d57318-2c6a-11e8-9729-02d73315df4e.png)

Thanks

**Comment by GrzesiekKozdroj** [comment]
npm install --dotenv-extended did not help me

**Comment by upulieh** [comment]
Mine was fixed by just a simple 
`npm install dotenv`

**Comment by Mohitp98** [comment]
**This worked for me**

> Initial env:
> `NODE_ENV=production`

it was failing to install dependencies

then I changed env: 

> `NODE_ENV=development`

I was able to resolve dependencies and start the application

**Comment by Ortovoxx** [comment]
> Mine was fixed by just a simple
> `npm install dotenv`

Worked for me! I am pretty sure there was a new version released that messed with something.

All fixed now though thanks!

**Comment by HershKirsh** [comment]
`npm install dotenv @latest` worked for me

**Comment by JoshBowdenConcepts** [comment]
none of the above solutions worked for me. I am not sure why

**Comment by OpiiuM** [comment]
npm i dotenv-extended
"require("dotevn").config()", change on "require('dotenv-extended').load()"

**Comment by SametReyiz61** [comment]
github da console nerde

**Comment by OpiiuM** [comment]
sorry, about what you?

вс, 4 апр. 2021 г. в 20:15, SametReyiz61 ***@***.***>:

**Comment by ThomasHang** [comment]
> same here, I have this issue in a container (Gitlab CI).

Did you solve it

**Comment by AhmeddHabib** [comment]
Hi, i have the same problem! did anyone fix it to help me

**Comment by Annetastar** [comment]
> Мой был исправлен простым `npm install dotenv`

Thanks! This works for me!

**Comment by JoaoG23** [comment]
i solve my problem with **npm install dotenv-extended**, but it's not good because all times that anyone clone my project must install this package for using of my app. ..😅,did am i wrong about that?!🤔

**Comment by 6str** [comment]
thanks
npm install dotenv 
fixed for me too. easy when you know
