### ISSUE TITLE
Can we get access to the mobile clients source code as well ?

### ISSUE THREAD

**Issue by rhulha** [JedWatson/sydjs-site#46]
Hey Keystone and Sydjs team,

I know I am greedy, KeystoneJS and Sydjs are great to have as open source in the first place
and I have no right to ask for anything more, but I thought I'd ask just in case...

Can we get access to the mobile clients source code as well ?

**Comment by JedWatson** [comment]
@rhulha do you mean this? https://github.com/bladey/sydjs-app

**Comment by rhulha** [comment]
You guys rock, thanks mate!

**Comment by JedWatson** [comment]
No problem :)
