### ISSUE TITLE
LESS variable missing - @select-menu-max-height

### ISSUE THREAD

**Issue by cantuket** [JedWatson/sydjs-site#49]
Hi Guys,

I have a small error in the LESS file shown below. The variable is defined in the default.less file so I'm a pretty confused as to what is causing the problem.  I just commented it out and everything is working fine.

```
Name Error thrown for request: /keystone/styles/keystone.css
{ type: 'Name',
  message: 'variable @select-menu-max-height is undefined',
  filename: '/Users/kylegermaine/keystone_demo2/node_modules/keystone/node_modules/react-select/less/select-menu.less',
  index: 732,
  line: 21,
  callLine: NaN,
  callExtract: undefined,
  column: 13,
  extract: 
   [ '\tmargin-top: -1px;',
     '\tmax-height: @select-menu-max-height;',
     '\tposition: absolute;' ] }
```

Thanks for the amazing head-start project!  I'm just getting started with Keystone and you've saved me a ton of time. Very excited to get your Cordova project connect as well.

Thanks!!!
~ Kyle

**Comment by hatzipanis** [comment]
In project root delete node_modules folder, then in package.json edit `keystone` to be `~0.3.0` and run `npm install` again. Ran into this myself and later realised it's a bug they've since fixed.

**Comment by hatzipanis** [comment]
Update `keystone` package in package.json to be `~0.3.0`. Ran into this myself and later realised it's a bug they've since fixed.

**Comment by cantuket** [comment]
Thanks hatzipanis you just made my day!

This also fixed the date-picker issue I just posted.
