### ISSUE TITLE
Passport initialization for social login

### ISSUE THREAD

**Issue by connor11528** [JedWatson/sydjs-site#93]
I am trying to implement oauth for github using passport into my keystone.js app.

I have been using this repo as a guide. In my console I am getting to **lib/auth/github.js**

```
[services.github] - Authentication workflow detected, attempting to request access...
```

However I get a 500 error in the browser:

```
Sorry, an error occurred loading the page (500)

passport.initialize() middleware not in use
```

How or where do you initialize the passport middleware? I am searching through the repo and cannot find a call to `passport.initialize(`

**Comment by cleechtech** [comment]
Got a little bit past this using **routes/auth/app.js** **routes/auth/confirm.js**. What is the github registered url callback for this application? (Am kind of a n00b but really excited about putting social auth into the power of a keystone app)

**Comment by enraiser** [comment]
what do you mean by using routes/auth/app.js and routes/auth/confirm.js.  .they are already being used.  
Can someone elaborate the solution.

I generally think that there is no one on the planet to answer question about keystoneJS. on stackoverflow as well.

**Comment by oliverwh** [comment]
There is an issue with ur callback url for sure

**Comment by enraiser** [comment]
Yes you are right, the callback URL must have  **?cb=true**  at the end
`http://localhost:3003/auth/facebook?cb=true`

I have written a [detailed blog](https://www.enraiser.com/blog/nodejs/sydjs-keystonejs-issues-with-social-login-using-passport) on resolving all issues [here](https://www.enraiser.com/blog/nodejs/sydjs-keystonejs-issues-with-social-login-using-passport).

**Comment by connor11528** [comment]
Okay got it thank you!
