### ISSUE TITLE
Yo keystone produced flawed package.json, comma missing before gulp

### ISSUE THREAD

**Issue by rpbeltran** [JedWatson/sydjs-site#95]
I ran through the generator for keystone, and included the option to install gulp in my project. I then ran `npm install` and it generated all my files. I tried to run the project and got an error that said:

```
npm ERR! Failed to parse son
npm ERR! Unexpected token 'g' at 21:6
npm ERR!     "gulp": "^3.7.0",
npm ERR!      ^
```

That looked to me like the `package.json`, so I opened it up, and there was a comma missing. It had generated:

```
...
"eslint-config-keystone": "^2.3.1",
    "eslint-plugin-react": "^5.1.1"
    "gulp": "^3.7.0",
...
```

in the `package.json`. This was of course a trivial error to fix in the output, and didn't take long to fix, but still, I don't think it should be doing that. 

This was in OS X with a fresh install of keystone (just started looking into it today), and also Yo (I had never installed it until today either), and I followed the generator instructions from the websites getting started page. Hope that helps.

**Comment by JedWatson** [comment]
Thanks for that! I just published a fairly major update to the generator, and it seems the configuration options you selected slipped through with that broken syntax. I've fixed it and am about to publish an update.
